# generated by datamodel-codegen:
#   filename:  models.json

from __future__ import annotations

from pydantic import BaseModel, confloat


class MamaContracts(BaseModel):
    pass


class Prediction(BaseModel):
    score: confloat(ge=0.0, le=1.0)
    label: str


class ModalityResult(BaseModel):
    modality: str
    prediction: Prediction


class PredictRequest(BaseModel):
    case_ref: str


class FusionRequest(BaseModel):
    results: list[ModalityResult]


class FusionResult(BaseModel):
    score: confloat(ge=0.0, le=1.0)
    label: str
    contributions: dict[str, float]


class ClinicalAlert(BaseModel):
    case_ref: str
    level: str
    fusion: FusionResult
